### ISSUE TITLE
Double tap to zoom

### ISSUE THREAD

**Issue by ericliou** [ddvk/remarkable-hacks#71] opened 2020-09-16 10:45 UTC
For people that read PDFs, we do a lot of zoom in and out. Specially when reading papers, many have two columns with tiny font, the zoom is almost required. But the experience for zooming in/out and pan is pretty bad.

To zoom in, the interactions are these:
1) tap or swipe to show toolbar
2) tap zoom tool
3) tap zoom in
4) tap zoom level select box
5) tap desired zoom level
6) tap on the desired region to center
7) sigh and complain

If possible, I'd like to suggest:
1) double tap on the page (finger). This uses the place the user tapped as zoom center and zooms to the level they last used
2) smile and get a beer for dobum

**Comment by ddvk** [comment] 2020-09-16 13:15
for now can offer you pinch in /out in reading mode

**Comment by ddvk** [comment] 2020-09-16 19:16
added in the latest commits, could you test it?

**Comment by ericliou** [comment] 2020-09-16 22:04
wow so fast!

I see that it goes in the switch case if it's a rM2 version?
https://github.com/ddvk/remarkable-hacks/commit/7e990f92a104e52df6019b92b81572bf285d2582#diff-95d84854652267a9fbccfca9b0f08f93R73

I'm still waiting my rM2 though.

**Comment by ddvk** [comment] 2020-09-16 22:11
should work on the rm1 as well (2.3.0.16)

**Comment by ddvk** [comment] 2020-09-17 06:25
made a 2.2.0.48 patch

**Comment by ericliou** [comment] 2020-09-17 12:02
It's working really well. I'm in love.

**Comment by ericliou** [comment] 2020-09-17 12:06
The only improvement I see is to remember the last zoom (vs default zoom of 200%).

And how do I get you the promised beer?

**Comment by Tridens92** [comment] 2020-09-17 16:38
At least in my testing with version 10.07, the thumbnail that you use to move the zoomed region is no longer responsive.

**Comment by ddvk** [comment] 2020-09-17 17:18
that was by design ( some people complain that they touch it when writing)

will need a toggle

**Comment by computemachines** [comment] 2020-09-17 19:03
It would be nice if swiping while zoomed in pans the view instead of flipping the page

**Comment by sethmnielsen** [comment] 2020-09-17 19:57
@Tridens92 It works with the marker, just not fingers.

This pinch-and-zoom is fantastic, by the way!

**Comment by ddvk** [comment] 2020-09-17 21:34
> It would be nice if swiping while zoomed in pans the view instead of flipping the page

ok, test it then

**Comment by Tridens92** [comment] 2020-09-17 22:01
I like the *idea* of the pinch zoom, but I'm having lots of trouble with it activating when I'm just writing.  It's happening so often that I'm needing to revert to an older version of the hack without pinch and zoom.  Can we get a toggle for this and/or perhaps look at the sensitivity of it?  I don't know if this has anything to do with it activating while writing, but I'm left-handed.

thanks!

**Comment by sethmnielsen** [comment] 2020-09-17 22:06
@ddvk Just tried it and it's working great! But only in portrait mode. 

In landscape, the screen still moves as if you were swiping in portrait mode. So while in landscape, a swipe to the right -> pans upward, left -> pans downward, up -> pans left, and down -> right. 
- "right -> pans upward" meaning that touching left part of screen and moving finger to the right makes the screen pan up the page
- This is in right-handed landscape, so left-handed would be the reverse of that

**Comment by ddvk** [comment] 2020-09-17 22:33
i ll add a toggle

**Comment by ddvk** [comment] 2020-09-18 08:05
i added a toggle and tweaked the threshold, also landscape mode should be fixed

**Comment by Tridens92** [comment] 2020-09-18 16:23
@ddvk, at first try, this tweaking of the threshold has made all of the difference for me.  No unintentional zooms yet during writing, and the toggle is there now as well.  As always, thanks so much for your great work.

**Comment by StLa1** [comment] 2020-09-19 19:43
The zoom regularly triggers because of palm, but not sure you can do anything about it, coding palm rejection is super tricky. Also sometimes the rM crashes when pinching to zoom while already in zoom (to increase zoom level), but agin, not sure you can do anything.

Else it's an incredible feature, thx !

**Comment by ddvk** [comment] 2020-09-19 20:51
there is an option to disable pinchzoom, cant do much about the crashing (if unpatched also crashes)

**Comment by Tridens92** [comment] 2020-09-19 22:46
Will rm1 2.3.0.16 also get the disable toggle and the threshold tweak?  Want to make sure before I let my rM1 upgrade from 2.2.0.48.  Thanks.

**Comment by ddvk** [comment] 2020-09-19 22:51
yes, this is the preferred version

**Comment by sethmnielsen** [comment] 2020-09-20 05:16
@ddvk Is it available for 2.3.0.16 though? I updated my RM1 to 2.3.0.16 and I downloaded the latest patch (12.07), but I don't see the toggle anywhere. Also, landscape mode is still messed up. The README for 12.07 only says "move zoom" as the description, so maybe the toggle/threshold patch didn't get pushed?

**Comment by ddvk** [comment] 2020-09-20 19:33
sorry, had forgotten to push it

**Comment by bongotai** [comment] 2020-09-23 02:33
@ddvk just logged in to say thank you for pushing the latest changes, and as well for the general endeavour! the RM1 without the hacks would be a lot less useful. BIG thank you!

**Comment by ddvk** [comment] 2020-10-14 14:55
closing as mostly fixed

**Closed by ddvk** 2020-10-14 14:55 UTC
