### ISSUE TITLE
Folders in normal list view messed up in patch 30.2.02-0

### ISSUE THREAD

**Issue by martin-braun** [ddvk/remarkable-hacks#416] opened 2022-02-16 13:11 UTC
My previous version was 2.11.0.442, right after #388 was closed, but before the final commits in this issue (to address the concern of @rex-banner) were made. I uninstalled this version, removed all traces (by confirming with `y` on uninstallation), then I updated and patched the new version. I notice that the normal list view looks like this (I have many folders in the root directory, they all are stacked on the top left corner): 

![PXL_20220216_123322669](https://user-images.githubusercontent.com/24259245/154269245-1909238b-a55f-40a1-b841-831362b9bcb0.jpeg)

Every other mode (compact list view, grid view) work as intended, no blocker for me, but certainly a bug.

**Comment by ddvk** [comment] 2022-02-16 20:19
🙈 i missed that, should be fixed now

**Comment by martin-braun** [comment] 2022-02-16 21:20
@ddvk Now the compact view is broke. Please toggle between normal and compact to see the problem in action, please.

**Comment by dansbandit** [comment] 2022-02-16 21:23
How do you reproduce it? I have the latest hacks and when press "Normal" and "Compact" everything works as it should.

**Comment by martin-braun** [comment] 2022-02-16 21:28
> How do you reproduce it? I have the latest hacks and when I press "Normal" and "Compact" everything works as it should.

Keep trying, it will only happen every 2nd time you go from normal to compact list view.

**Comment by dansbandit** [comment] 2022-02-16 21:48
I've toggled like 50 times now and I still can't reproduce the bug. Maybe someone else have the same bug?

**Comment by Tridens92** [comment] 2022-02-17 00:28
I'm having similar trouble.  I found my way here after realizing my folders at the root level were not displaying...only my documents.  When I tried to toggle to compact mode, my folders appeared.  Trying to toggle back to Normal mode is not working.

**Comment by ishanina** [comment] 2022-02-17 01:01
For me, folders don't appear at all in the patched version.

**Comment by ishanina** [comment] 2022-02-17 01:03
To clarify, folders appear in list mode, but not grid mode for me

**Comment by Tridens92** [comment] 2022-02-17 01:27
I had to swipe down in order for the folders to appear in grid mode.

**Comment by ishanina** [comment] 2022-02-17 03:40
I was able to make the folders appear in grid mode by first switching to compact list mode, and then switching back to grid mode

**Comment by ddvk** [comment] 2022-02-17 11:55
another try...

**Comment by martin-braun** [comment] 2022-02-17 12:22
@ddvk Unfortunately, this is still happening to me: [youtu.be/ODWN4TY1bJA](https://youtu.be/ODWN4TY1bJA)

The only difference is that I can see folders and files on initial view perfectly fine until I keep switching between the modes. Here are precise steps to reproduce:

1. On the previous version go in compact list view
2. Install the hack update temporary, it seems to look alright after booting
3. Switch to normal list view, this looks right as well
4. Now switch back to compact list view, things don't look right anymore

Files and folders should overlap by that time, which is incorrect.

**Comment by martin-braun** [comment] 2022-02-17 15:06
@ddvk Automagic auto patching (no arg) still installs patch_30.2.05.

**Comment by ddvk** [comment] 2022-02-17 15:25
> @ddvk Automagic auto patching (no arg) still installs patch_30.2.05.

05 is the last one for rm2, is it still broken?

**Comment by martin-braun** [comment] 2022-02-17 16:21
@ddvk Yes, for me it is broken, but only partially. I installed it permanently, yet every other switch from normal to compact list view results in the strange behavior that you can see in the YouTube video I linked above. Are there any logs I can share? 

Personally it is not a deal breaker, since I only use compact view, but it's really strange and should be addressed. I didn't install anything other than your hack, so there should be no foreign side effects.

**Comment by ishanina** [comment] 2022-02-17 16:58
For me it works now, thanks!

**Comment by Tridens92** [comment] 2022-02-17 17:07
I'm still needing to swipe down to reveal my folders (rM1).

**Comment by ddvk** [comment] 2022-02-17 19:29
it had been always buggy, but i didn't have so many folders, so didn't reproduce it every time

**Comment by Tridens92** [comment] 2022-02-17 19:52
Hi @ddvk !  Unfortunately, I'm still having the issue on my rM1.  Here's what I'm seeing:

1) When the device first reboots from installing the hack, I DO see folders in grid view.
2) If I switch to List view, I see no folders.  Swiping down does not reveal them
3) Switching Sort mode makes them appear
4) Switching back to Grid view, and folders are no longer visible
5) But swiping down then reveals them

I hope this helps you troubleshoot.  FYI, I have 25 folders at the root level.

Thanks so much for your continued dedication to this project @ddvk !  I'm happily making another donation!

**Comment by ddvk** [comment] 2022-02-17 19:55
@Tridens92 and the version is 30.1.07?

**Comment by ddvk** [comment] 2022-02-17 23:54
@Tridens92 try again :)

**Comment by Tridens92** [comment] 2022-02-18 00:48
So far, so good, @ddvk !  Thanks so much for the quick fix.  I'll be curious to see if it fixes @martin-braun 's similar issues.

**Closed** 2022-02-18 11:51 UTC
