### ISSUE TITLE
New SW 

### ISSUE THREAD

**Issue by 303Jeep** [ddvk/remarkable-hacks#505] opened 2023-01-29 18:09 UTC
Is there any timeline when a new version will be compatible with 3.0.4.1305?

**Comment by Eeems** [comment] 2023-01-29 18:35
This is a duplicate of #496

**Comment by 303Jeep** [comment] 2023-01-29 18:37
Apologies, didn't go far enough down the list to see this was a duplicate

**Closed** 2023-01-29 18:37 UTC
