### ISSUE TITLE
Lamy button switches back to the wrong pen after erasing

### ISSUE THREAD

**Issue by FlorianKempenich** [ddvk/remarkable-hacks#193] opened 2021-01-20 16:15 UTC
Hi,

For a couple of weeks (months?), there's a weird behavior that happens when using the lamy button / eraser:

- On click (or hold) the eraser gets enabled. All good.
- But then on second click (or release), _sometimes_ it'll switch back to the wrong pen, or even the select tool.

The pen I mainly use is the calligraphy pen, and often it'll switch to the fine liner, sometimes the ballpoint, or even the select tool.

Usually, if I trigger the eraser again, then it switches back to my calligraphy pen.
If you need more info, or if you want me to run some tests, let me know

**Comment by Tridens92** [comment] 2021-01-20 16:25
I'm thrilled to see I'm not the only one!  Thought I was going crazy, @FlorianKempenich !  I have been using the remarkable-hacks and the Lamy hack since the latter was released.  I have definitely noticed quirky behavior in the last month or so.  I reported it here:
[https://github.com/ddvk/remarkable-hacks/issues/126#issuecomment-759814433](url)

It's especially problematic for me when the last used tool is the Select tool, as I've inadvertently pasted over top of something I'm writing on because there was something stored on the clipboard, and while erasing, the tool suddenly changed from my pen back to the select tool.

@ddvk, could you kindly let us know what might have happened in the last month (or so, not exactly sure of timeframe) that might account for this change?  It's definitely a new experience for me in that general timeframe, and I use my rM1 an average of 4 hours a day, so I've got lots of time under my belt to notice.

Thanks!

**Comment by ddvk** [comment] 2021-01-20 16:36
it probably came with the combination of double click undo / single click toggle.

what could be happening:

if the pen is out of range (> 2cm), you click the button, then quickly erase something and move it out of range, that will be interpreted as a click.

possible fixes:
i could reduce the single click to 300ms 

remove tool togling / make it an option

**Comment by Tridens92** [comment] 2021-01-20 16:44
Thanks, @ddvk.  I personally would love **both** or those options.  I was already going to write and ask for the 500ms to be reduced, as for me, that's way too long (because the pen doesn't need to be flipped to get to the eraser on the opposite side of pen, you're not moving the pen at all to engage the eraser, so shorter is better).

And the toggle option would make everyone happy, as they could turn it off if they don't want it at all, or turn if off temporarily when using only one tool and erasing.

Thanks!

**Comment by ddvk** [comment] 2021-01-20 18:46
i pushed a patch with reduced timing

**Comment by FlorianKempenich** [comment] 2021-01-21 10:42
Hi @ddvk ,

Thanks for your response and the very quick fix. I did not understand how reducing the delay would solve the problem to be honest. 
Whether a "false" click is detected or not would not have any impact on switching back to the wrong tool, would it?

Either way, I've ran the automatic 5 min ago, so I should have the latest patch and I'll let you know if the issue keeps appearing or not :) 

Thanks again

**Comment by FlorianKempenich** [comment] 2021-01-21 10:46
Update. The issue is still here.

I can't reproduce reliably, but here is what will (sometimes) happen:
- The pen is in range the whole time
- I have calligraphy pen enabled
- I hold the button to erase
- I erase
- I release the button to erase
- It switches back to calligraphy pen for half a second . . . _and then switches to the select tool_ <= **This is the problem**
  - Sometimes, instead of switching to the select tool, it'll switch to another type of pen instead.

**Comment by ddvk** [comment] 2021-01-21 11:45
how long do you hold the button pressed while erasing?

i will try to reproduce it, but
i ll add an option to disable the tool toggling then

**Comment by ddvk** [comment] 2021-01-22 08:07
i pushed another fix. 
btw, the select tool is saved as lasttool, so if you used select it will be used as the alternative tool

**Comment by Tridens92** [comment] 2021-01-22 13:15
Working great for me after initial testing, @ddvk.  Thanks!  Can you tell us what the new timings are?  Also, are you still intending to add a toggle for this switching feature or no?  Have a great weekend.

**Comment by ddvk** [comment] 2021-01-22 13:18
there was a bug with the double click timer, also now, after the pen makes a stroke it counts as hold

**Comment by Tridens92** [comment] 2021-02-07 14:29
> also now, after the pen makes a stroke it counts as hold

@ddvk , just dropping by after using the most recent version of the lamy hack to say that the above-quoted change makes a HUGE difference to my experience.  I write on my tablet a minimum of 12-14 hours a week in meetings, and this minor makes my experience infinitely better.  Just wanted to write and give another huge "thank you" for the work you do.  So...thank you!

**Comment by ddvk** [comment] 2021-02-11 08:20
closing this for now

**Closed by ddvk** 2021-02-11 08:20 UTC

**Comment by eloeffler-fhnw** [comment] 2021-02-26 09:59
I can't figure out how to reliably switch between modes now.
Hold to erase, ok.
Double click button to undo (wow! was that there before? nice!).

But is there still an intended way to switch to the last tool?
I can sometimes get it to work by pressing long, then short, I think.
But it's not working most of the time. 

Am I experiencing a bug or am I doing it wrong?

**Comment by crisandria** [comment] 2021-02-26 10:12
I am having the same issue switching between tools with the Lamy button. Most of the time I have to try 3 or 4 times before the switch takes. But then it may work on a single click for a bit, then need multiple clicks before the switch takes.

**Comment by eloeffler-fhnw** [comment] 2021-02-26 10:31
I just noticed that it works if you Just Hold It Differently™.

When clicking with my index finger instead of my thumb, I can let go faster and then it appears to be working. So this is also influenced by hand temperature :)

Is it possible to increase the switching time a bit, or would this revert the previous fix?

Thanks anyways :)

**Comment by dstango** [comment] 2021-02-26 11:49
I can confirm that it only works when it press & release the button rather quickly. Maybe the timing could be tweaked a little.
Besides that it would be great to have a display of the currently selected tool in the upper left corner (like in zen mode). That would at least reduce the uncertainty if the button press worked or not.
