### ISSUE TITLE
Layers button - potential bug and All Layers option in the cycle

### ISSUE THREAD

**Issue by Tridens92** [ddvk/remarkable-hacks#74] opened 2020-09-18 16:41 UTC
When I only have two layers (Template and Layer 1, by default), and then use the Layers button (the eye), it cycles between Template layer only, Layer 1 only, and then back to Template layer.  I can't get back to the "Normal" view of both template and Layer 1 without jumping to the default rm Layers icon and re-enabling both layers.  Could you please add "All Layers" to the rotation with the Eye button?  So it would function like: Template --> Layer 1 --> All Layers.

A related potential bug.  While testing this Eye button before posting this, I, for the first time, made a 2nd Layer (Called Layer 2).  I expected current functionality would do this: Template --> Layer 1 --> Layer 2.  However, it did not.  I was unable to view Layer 1 via the Eye button (had to use the original rM Layers function to re-enable it.

Thanks so much for considering both this suggestion and potential layers bug.

**Comment by StLa1** [comment] 2020-09-19 19:40
I'm pretty sure the omission of the "All layer" step in the cycle is on purpose, but it indeed makes no sense in term of UX.

The bug you found is actually more general: whenever you have n layers, the cycle will go as follows:
Template > Layer n > Template >... and will skip all other layers.

To sum up, the cycle should be: All layers (default) > Template > L1 > L2 >... > Ln > All layers > Template >....

**Comment by ddvk** [comment] 2020-09-20 19:33
It switcher only the current layer with the document

The general idea of the Eye was to toggle the visibility of the background, when you have a document you want to write on, so that 
you either see the things you write or the document.

**Comment by StLa1** [comment] 2020-09-22 15:59
Ah makes sense now

**Comment by ddvk** [comment] 2020-10-14 14:53
closing this, it is a feature not a bug

**Closed by ddvk** 2020-10-14 14:53 UTC
