### ISSUE TITLE
[Enhancement] Add blank page after this one...

### ISSUE THREAD

**Issue by mig2** [ddvk/remarkable-hacks#219] opened 2021-02-19 15:32 UTC
Thanks for all the amazing work here. It would be awesome if there were a hack to add a blank page to a PDF. The use case is e.g. working through a math paper where I run out of room in the margins (:-)) and would like to continue scribbling.... you may be able to do this with installation of pdftk...

**Comment by pstemper** [comment] 2021-02-19 15:41
I believe this is a duplicate of #218
https://github.com/ddvk/remarkable-hacks/issues/218

**Comment by ddvk** [comment] 2021-04-11 14:20
sorry, not possible, closing as duplicate

**Closed by ddvk** 2021-04-11 14:20 UTC
