### ISSUE TITLE
Bookmarks don't shift upon page insertion/deletion in the middle of the notebook

### ISSUE THREAD

**Issue by StLa1** [ddvk/remarkable-hacks#271] opened 2021-04-10 15:38 UTC
Imagine you have bookmarked pages 1 and 2.
You add a page between 1 and 2.
This new page will now carry the bookmark for the page now at place 3.

**Comment by pstemper** [comment] 2021-04-10 16:08
Duplicate of #179

**Comment by ddvk** [comment] 2021-04-12 19:14
yes, duplicate, will tackle it if I find a way to figure it out

**Closed by ddvk** 2021-04-12 19:14 UTC

**Comment by StLa1** [comment] 2021-04-13 18:12
@ddvk Couldn't this be a achieved by checking the amount of new or deleted pages upon page creation/deletion ? (saving page amount in a temp, then comparing temp and actual page count once the event is triggered, shifting bookmarks, then updating temp)
