### ISSUE TITLE
2.5.1 Compatible?

### ISSUE THREAD

**Issue by nathanwinklepleck** [ddvk/remarkable-hacks#230] opened 2021-03-02 13:50 UTC
I've got the new Remarkable 2 with firmware updated to 2.5.1. Will the existing 2.0.5 'hack' work for me and, if not, is there anything in the works for this updated firmware?

**Comment by Eeems** [comment] 2021-03-02 13:54
Duplicate of #206 and #217

**Closed** 2021-03-03 18:26 UTC
