### ISSUE TITLE
Hacks for Version 3.0.4.1305

### ISSUE THREAD

**Issue by GreGatosec** [ddvk/remarkable-hacks#499] opened 2023-01-06 12:53 UTC
Hi ddvk,
I a new Remarkable (2) happy owner and I'l like to use the hacks available here. I feel this is a awesome way to boost the usage of my tablet. I'tried, but as my tablet is using the last version of the OS, it fails.
I'd like to know if you have any plan to upgrade the hacks to this new version?
Many thanks,
GG

**Comment by Eeems** [comment] 2023-01-06 15:56
Duplicate of #496 496

**Closed** 2023-01-17 07:09 UTC
