### ISSUE TITLE
Inadvertently installed on new version 2.5.1.45 — works fine

### ISSUE THREAD

**Issue by RhvdG** [ddvk/remarkable-hacks#234] opened 2021-03-03 14:35 UTC
I didn't realise my brand new rM2 was running software version 2.5.1.45, not 2.5.0.27. The hacks installed just fine. This might be good to know for you coders.

**Comment by ddvk** [comment] 2021-03-03 15:41
well because supported was added, but the readme was not updated

**Comment by Eeems** [comment] 2021-03-03 15:41
Duplicate of #230, #206 and #217

**Comment by ddvk** [comment] 2021-03-03 15:53
i updated the readme

**Closed by ddvk** 2021-03-03 15:53 UTC
