### ISSUE TITLE
add support for 2.5.0.27

### ISSUE THREAD

**Issue by idnovic** [ddvk/remarkable-hacks#139] opened 2020-12-08 01:54 UTC
Please add support for the newest software release. 

I know it is brand new. Take your time.

**Comment by UnchartedSystems** [comment] 2020-12-08 02:58
What currently happens when updating to 2.5.0.27?

**Comment by Eeems** [comment] 2020-12-08 03:27
> What currently happens when updating to 2.5.0.27?

You'll be running 2.5.0.27 without hacks.

**Comment by ddvk** [comment] 2020-12-08 08:13
sure, i just need some time

**Comment by urazack** [comment] 2020-12-08 23:49
Thank you!

**Comment by ddvk** [comment] 2020-12-09 16:37
i've pushed an initial version, testers are welcome

**Comment by Snowflake6** [comment] 2020-12-10 17:08
Installed the hacks yesterday, all seems good except:  The hack to enable the button on the Lamy pen now works funny.  If you're writing and push the button you get an eraser.  When you release the button, it switches to the region-select tool.  Sometimes.

**Comment by ddvk** [comment] 2020-12-10 17:55
the timing was changed. short press is toggle last tool, double click undo,
hold > 1 sec is the normal erase

**Comment by Snowflake6** [comment] 2020-12-10 18:05
> the timing was changed. short press is toggle last tool, double click undo,
> hold > 1 sec is the normal erase

Ah, okay, that's what changed.  I was doing region moves as well, so it must have been switching to that as the "last tool."

Didn't know about the double-click-undo, but that is an excellent feature.  👍

**Comment by ddvk** [comment] 2020-12-10 18:12
thiugh, there seems to be a bug with the selection tool toggle

**Comment by Snowflake6** [comment] 2020-12-10 18:26
Hmm... Confirmed.  Steps to reproduce:

1. Select something on the page using rhe region select, and move it somewhere else.
2. Select the pen tool (i'm using the fineliner, if it matters).
3. Draw something.
4. Hold button, erase something.
5. Release button, selection goes back to pen tool.
6. Push/release button, selection goes briefly to eraser, then moves to selection tool.
7. Hold button (selection changes to eraser), erase something, release button (selection goes back to pen).
8. Push/release button, selection goes to eraser, then back to selection tool.

So it's working if you hold the button, but not if you tap it.  I typically hold the button so this may not be an issue for me.

**Comment by dstango** [comment] 2020-12-10 19:58
The new Lamy button timing works much better for me, thank you!

**Comment by jdschw** [comment] 2020-12-11 20:02
@ddvk quick question: Should I wait to update the patch until I get 2.5 from Remarkable? Or does the patch include 2.5 and therefore I can update your patched version immediately?

**Comment by ddvk** [comment] 2020-12-11 20:32
> @ddvk quick question: Should I wait to update the patch until I get 2.5 from Remarkable? Or does the patch include 2.5 and therefore I can update your patched version immediately?

no, the paych is a diff, and you need the official version first

**Comment by ddvk** [comment] 2020-12-13 16:15
closing as more or less fixed

**Closed by ddvk** 2020-12-13 16:15 UTC
