### ISSUE TITLE
RM updated to v 2.7.1.53

### ISSUE THREAD

**Issue by fatalkarma100** [ddvk/remarkable-hacks#313] opened 2021-06-06 00:03 UTC
Could you please update for latest release by RM to v 2.7.1.53?

Thank you.

**Comment by Eeems** [comment] 2021-06-06 00:39
Duplicate of #312 #311 and #304

**Comment by thetechnologyguy** [comment] 2021-06-07 08:19
2.7.1.53 is an official release.  I am not on beta and got it pushed this morning.  There is no sign of 2.8, think that is in beta.

Do we have to wait for 2.8 for an update or will you be pushing new code for 2.7.1.53

Thanks

**Comment by ai212983** [comment] 2021-06-07 11:36
It seems  @ddvk [chose to ignore](https://github.com/ddvk/remarkable-hacks/issues/311#issuecomment-854620147) 2.7.1.53 and wait for 2.8. 

So everyone updated to 2.7.1.53 can downgrade to previous version, [as described](https://github.com/ddvk/remarkable-hacks/issues/304#issuecomment-847997460) by @pstemper or wait til 2.8 is pushed to her device.

**Comment by pstemper** [comment] 2021-06-07 11:46
I wouldn't say @ddvk "chose to ignore."  You have to remember that making the patches and determining how/where to patch the actual OS image DOES take effort on @ddvk's part.  @ddvk isn't modifying source code and recompiling.  There is work involved to develop the patches, AND THEN determine where/how to patch the actual app running on the rM.  The decision was made (and in my option rightly so), to only  port the patches on "released" versions, and then only when @ddvk HAS THE TIME.  2.7.1.53 may be official, but it is still @ddvk's decision if it is worth the time when a new major revision may be out soon.  Remember, other then the few people that donate to this project, @ddvk is doing it for free and out of kindness.  It upsets me when people come here and COMPLAIN that @ddvk isn't "supporting them", or won't implement their "must have" idea.  Please remember people, this is something @ddvk is doing to try to help people.  If you don't like the "support" that you feel @ddvk is giving (or not giving) you, then you are free to write your own patches.  In the meantime, enjoy what @ddvk has given you for "free". Being a software developer myself I understand the frustrations people on BOTH side are feeling, but when you get something for free, you shouldn't be demanding anything, or complaining when you aren't given exactly what you want.

Sorry for the rant, and I am SURE I will get people blasting me for saying this, but I just needed to vent a little.  My apologies to those I have offended.
Thanks for listening to (reading) this.

**Comment by ai212983** [comment] 2021-06-07 11:53
@pstemper: I am wholeheartedly grateful to @ddvk and he is doing an awesome job for the community. That doesn't change the fact he chose to ignore 2.7.1.53 and wait for 2.8.  I do understand stating this may sound unpleasant or even offensive for some, and I am deeply sorry about that. That doesn't change aforementioned fact either.

**Comment by ddvk** [comment] 2021-06-07 12:36
thank everyone for the support, let's keep our cool. everyone makes mistakes or has wrong assumptions. I assumed that the 2.8 is release will be rolling out soon, but i was wrong.

if I find the time, i'll patch the x.1.53 in the next days. i've had to deal with other stuff recently and i'm swamped at work

**Comment by ai212983** [comment] 2021-06-07 12:39
@ddvk My appreciation for you, sir, just jumped even higher. Very professional and proper response. And thank you for your awesome work!

**Comment by pstemper** [comment] 2021-06-07 12:39
@ddvk, no problem.  All is cool on my side.  @ai212983 wasn't offending me (and hopefully I didn't offend them!)

**Comment by thetechnologyguy** [comment] 2021-06-07 15:19
Thanks for being so responsive.

**Comment by dstango** [comment] 2021-06-07 15:28
I just saw a patch for the rm2 ...
Does anyone know: Is version 2.7.1.53 only released for rm2 or also for rm1?

**Comment by ddvk** [comment] 2021-06-07 15:42
> I just saw a patch for the rm2 ...
> Does anyone know: Is version 2.7.1.53 only released for rm2 or also for rm1?

 i couldn't find an official on for the rm1

**Comment by dstango** [comment] 2021-06-07 15:58
thanks :-)

**Comment by GeorgLink** [comment] 2021-06-07 18:23
I confirm that the install worked for my rm2 v2.7.1.53. - Thanks!

**Comment by pstemper** [comment] 2021-06-07 18:48
Working on mine also!
Thanks @ddvk !!

**Comment by gwtaylor** [comment] 2021-06-07 19:31
@pstemper I also wanted to say thanks for those excellent instructions in #304 on rolling back to 2.7.1.51 using the fallback partition. It felt great not blindly following commands but learning something in the process!

**Comment by pstemper** [comment] 2021-06-07 19:34
@gwtaylor No problem!  Glad I could help!

**Comment by Tridens92** [comment] 2021-06-07 21:49
> @pstemper I also wanted to say thanks for those excellent instructions in #304 on rolling back to 2.7.1.51 using the fallback partition. It felt great not blindly following commands but learning something in the process!

I totally agree...I just went to read the post you referenced.  I don't even need to do this, but appreciate the work @pstemper put in in composing such a time-intensive and clear post.  Well done, and thanks for your contribution to the community!

**Comment by fatalkarma100** [comment] 2021-06-07 21:53
@ddvk Thank you so much!

**Comment by pstemper** [comment] 2021-06-07 22:10
@Tridens92 Again, NO PROBLEM!!  I was happy to do it, and it makes me even happier that it helped people resolve any issues, and/or learn more about how the device works.  I have actually learned a LOT myself from comments @ddvk and MANY others have posted up here (too many people to list all their names), so I am glad I can be counted among those people who are helping others.

**Comment by Snowflake6** [comment] 2021-06-08 15:30
FYI - 2.8.0.86 dropped on my rM1 on Sunday the 6th.

**Comment by pstemper** [comment] 2021-06-08 15:36
@Snowflake6 Are you enrolled in the BETA program, or is this an official release?

**Comment by Snowflake6** [comment] 2021-06-08 15:39
@pstemper i'm in the Beta program, but this looks like an Official release.  There's nothing mentioning it's a Beta release in the release notes, so I thought it might be public.

Highlights:  Ability to merge layers, and it now remembers your favorite pen when you open a new document.

**Comment by pstemper** [comment] 2021-06-08 15:41
@Snowflake6 I am pretty sure it is still beta though.  The rM website does not talk about 2.8 yet, and when I was in the beta program myself, the beta's did NOT indicate they were betas.  :(

**Comment by Snowflake6** [comment] 2021-06-08 15:42
@pstemper Okay, that could be my mistake.  I thought when I enrolled the first (beta) release I received said something in the release notes about it being Beta... I could be wrong.

**Comment by Snowflake6** [comment] 2021-06-08 15:44
What's more annoying is that I just noticed that they updated the "End user agreement" for the Beta program and didn't notify me.  When I enrolled, it said *nothing* about installing third-party software.  Now it says that a condition of participating is that you cannot install any third-party software.  Oh well, I didn't agree to that, so it doesn't apply... :)

**Comment by pstemper** [comment] 2021-06-08 15:44
@Snowflake6 Not a problem!!  It is a bit deceiving.  You would think it would tell you it is a beta it is installing, but then I guess they can't just "roll out" the same update if they decide it no longer needs to be in beta (they would need to modify the notes to remove the beta notification.)

**Comment by pstemper** [comment] 2021-06-08 15:46
@Snowflake6 Interesting, I thought when I enrolled it said that from the beginning, but then again I may have enrolled just slightly after you.  Who knows.  I removed myself from the beta's anyway, as I can't work without the ddvk patches anymore.  I am hooked!!  :)

**Comment by Snowflake6** [comment] 2021-06-08 15:51
I'm fast coming to the same decision.  I like the idea of having the latest software, but I can't have the features coming and going like this.  Fundamentally I need oxide working again, but that's a discussion for another repository.

**Comment by PkW4v3** [comment] 2021-06-18 09:46
On my RM1 I got the 2.8.0.98 update without beta:
https://ibb.co/sVhdMqW

Works with this machine-id: ddf83d910e834f9fa2fc2351b6f1ce80

**Closed** 2021-06-18 18:48 UTC
