### ISSUE TITLE
I can't install automagic in rM2 2.6.2.75

### ISSUE THREAD

**Issue by wutever123** [ddvk/remarkable-hacks#292] opened 2021-05-02 18:36 UTC
I know nothing about code and I failed from the first step, how should I deal with this or where to find solution, thanks!

```
C:\Users\User> ssh root@10.11.99.1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
(somethingsomethingsomethingsomethingsomethingsomething)
Please contact your system administrator.
Add correct host key in C:\\Users\\User/.ssh/known_hosts to get rid of this message.
Offending RSA key in C:\\Users\\User/.ssh/known_hosts:1
RSA host key for 10.11.99.1 has changed and you have requested strict checking.
Host key verification failed.
```

**Comment by tzcone** [comment] 2021-05-02 18:47
https://stackabuse.com/how-to-fix-warning-remote-host-identification-has-changed-on-mac-and-linux/

**Comment by Eeems** [comment] 2021-05-02 21:27
Duplicate of #265

The link provided by @tzcone has instructions on how to resolve this. It's not an issue with the script, but a side effect of how reMarkable does upgrades. Every time the device is upgraded, a new host key is generated for the device, which means that the previous key is no longer used when connecting. This means that your computer will not trust the device and refuse to connect. All you need to do is clear the remembered fingerprint of the key from `~/.ssh/known_hosts` and try again. At which time it will ask you if you want to remember the new fingerprint.

According to your log, the fingerprint for your reMarkable is line one of `C:\\Users\User\.ssh\known_hosts`, where `User` is your username on your computer.

**Comment by ddvk** [comment] 2021-05-10 21:50
what @Eeems  wrote. the easiest is to just delete  `known_hosts`

**Closed by ddvk** 2021-05-10 21:50 UTC
