### ISSUE TITLE
SW v3 - update

### ISSUE THREAD

**Issue by fatalkarma100** [ddvk/remarkable-hacks#501] opened 2023-01-07 23:18 UTC
Thanks for all your hard work.  When do you think you might work on update for v3 software?

**Comment by klimeryk** [comment] 2023-01-09 13:32
Duplicate of #496 - see that issue for the newest updates 🙇 Looks like you're already on that thread, so it might be good to close this issue.

**Closed** 2023-01-09 23:28 UTC
